title: The World of Arta
description: The recorded history of Arta and it's newest band of adventurers
theme: just-the-docs

url: https://lawdaniel.github.io/arta
logo: "/assets/images/nat1_logo.png"
favicon_ico: "/assets/images/favicon.ico"

aux_links:
  Template Repository: https://github.com/lawdaniel/arta
